version: "2"
checks:
  similar-code:
    enabled: true
    config:
      threshold: 60
  method-complexity:
    config:
      threshold: 10
  method-lines:
    config:
      threshold: 30
plugins:
  eslint:
    enabled: true
    checks:
      max-lines-per-function:
        enabled: false
exclude_patterns:
  - "config/"
  - "db/"
  - "dist/"
  - "features/"
  - "**/node_modules/"
  - "script/"
  - "**/spec/"
  - "**/test/"
  - "**/tests/"
  - "Tests/"
  - "**/vendor/"
  - "**/*_test.go"
  - "**/*.d.ts"
  - ".editorconfig"
  - ".eslintrc.json"
  - ".gitignore"
  - "Procfile"
  - "client/build/"
  - "client/public"
  - "client/src/assets/*.js"
  - "client/src/assets/*.json"
  - "*.md"
  - "**/*.test.js"
  - "*.yml"
  - "*.json"
  - "**/*.json"
  - "**/*.svg"
  - "**/*.ttf"
  - "**/*.eot"
  - "**/*.otf"
  - "**/*.woff"
  - "**/*.html"
  - "**/*.png"
  - "**/*.txt"
  - "*.lock"
  - ".codeclimate.json"
  - "client/.testSetup.js"
  - "**/*.css"
  - "**/.eslintrc.json"
  - ".travis.yml"
  - ".eslintrc.json"
  - ".testSetup.js"
