version: "2"
checks:
  similar-code:
    enabled: true
    config:
      threshold: 60
  method-complexity:
    config:
      threshold: 10
plugins:
 eslint:
  enabled: true
exclude_patterns:
 - "config/"
 - "db/"
 - "dist/"
 - "features/"
 - "**/node_modules/"
 - "script/"
 - "**/spec/"
 - "**/test/"
 - "**/tests/"
 - "Tests/"
 - "**/vendor/"
 - "**/*_test.go"
 - "**/*.d.ts"
 - ".editorconfig"
 - ".eslintrc.json"
 - ".gitignore"
 - "Procfile"
 - "client/build/"
 - "client/public"
 - "*.md"
 - "**/*.test.js"
 - "*.yml"
 - "*.json"
 - "**/*.json"
 - "**/*.scss"
 - "**/*.svg"
 - "**/*.ttf"
 - "**/*.eot"
 - "**/*.otf"
 - "**/*.woff"
 - "**/*.html"
 - "**/*.png"
 - "**/*.txt"
 - "*.lock"
 - ".babelrc"
 - ".codeclimate.json"
 - "client/.testSetup.js"
 - "**/*.css"
 - "**/.eslintrc.json"
 - ".travis.yml"
 - ".eslintrc.json"
 - ".testSetup.js"