language: node_js
node_js:
  - "8"
cache: yarn
addons:
    code_climate:
      repo_token:
        secure: "cp2dI1mLqpwhvsIVsB0tWgTZNSSMSqSsubJtXN/2PZipQ0HlPSOQhwG4rcMObgYvodz0EgjtAYlPXw9i5yf57nGZQ6mRxcvlxtJ+hlveifYnT4yCx/IWnl4jgqKHrXBxT6jCbCI9MOKYnv6x9pZlEdKFMiUpMB2lz7SDGY9ODB3GQYC1A1Zad5yQbV0E1A8oHbDW3gge0Rj3R1l60WpxZBpbtj5U6fslFx6a8ZGjm25rxyIHPM5bFhfAj4xo/WaVZwDz23JCFdsvFhOGoyzNJkDljFdnWFXFedVxLrUYPeC4WG70sG4CjL62bxgQ92wLkPigwm+nkh/3WUm2nOmJVM5xnwekObAU8jgUE6FnRuyZfXTBoYpL/4wIS/CK/GvcY8fyHot/KL1eEhIk8LvuhVUBXpUIfrKR2Mf8luuDbDD9cwicLwKELQYU0IunaXCX96ML53vv5pb4sunlpL6gmZZ3c61Xzrjk1YWuj4RB5GuAtKul6LAahcMUI78h+hNmk+9kb/0LPo62uFkfhPamNBN9HI0muCegXwmyCvfaeK7+CCUV0yJgfvSf0Unac+hL1Y9bBvOXmcpiT33wEkESuO8msrc1i6Lj33BpCJXG0jCavLofTlyIz41Gm8VuQO3Z5uFKJKc6UYADlRhQezB70mKAAHiU+5uES5P2PMIwYRI="
install:
  - yarn global add cross-env
  - yarn global add codecov
  - yarn global add codeclimate-test-reporter
after_success:
  - yarn report-coverage
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: bQeh4mdbx+NQ6bEb5Gfzv2WR6N9IwmxuWrsqMJzAhXV05A8K5Z57ULSXHgAeuDTHkg0vB6K+Ok+igKHxLFcFBev/LC7EFesOQjF7ht4x+GMiXQ3RGlP1l2lfGtw4phPUMyID7h8jwNJ27Ayee4GyyNBbjVxNAP7zR+DLJSzKaBDlrZmCL1n6ue1FN0R+MM29ER8QUWhfW410wLkVn1MOavqbrTQGD1qceKTbzL0rbOXnWr5UuKQijf9hWLps+w/lzYf6HAA0Q6JJCFem3Jvsf/6oA+RAmHLjZnpoetk4Hi8o1ldqiIpp7EbXJVQ8ZhEeZ2V2ZgGSxubUeJrj059RG4lwQL8lmb4TqLux/LUaZYurlLIybuIMkBu97n8+y4IyvvR3CBqHusc5Ezc2ddQK1Ys3y/dCB/hpZzmdPYVZ6FU7rhIw+1bqToQARmEvA5hM/VX2o/oIpOraK2u82iPn+trC3pjQMo/dpZye3DJ7SfP5juz4xGzFDDQssB4ffJTa4fKF18upUSPPiLdvsOCdjLXrf7uVnHIXDvpRSyqM2HNrhLC5CCxKH0KNh/p5CXaZiQCgB1G1fAE6DVNk6b7yOg2TM0FHBJ9UKSPvW9KwlMn8asrEhzeD3+LuJI/lhJ5zSSTBvvIf4PKt99C68INWvG50IcP8oY5YQ9is4Y3JmmQ=
